<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: oli_v_ier
 * Date: Sun, 29 Jan 2012 23:48:18 +0100
 */

$conf['title'] = 'Randonner leger ou ultra-léger';
$conf['start'] = 'accueil_du_wiki';
$conf['lang'] = 'fr';
$conf['template'] = 'RL';
$conf['license'] = 'cc-by-sa';
$conf['recent'] = 100;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['relnofollow'] = 0;
$conf['subscribers'] = 1;

// end auto-generated content
